version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: itakuroso-backend
    restart: always
    ports:
      - '3000:3000'

    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
